# This workflow builds the application for pull requests and pushes to master

name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Run tests
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Build application
        working-directory: application
        run: ./gradlew build --stacktrace
        
      - name: Zip build reports
        if: always()
        run: zip -r reports.zip **/build/reports 
        
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: reports
          path: reports.zip
