# This workflow deploys all resources that are specific to the application, but not the application itself.

name: 03 - Manually create the application environment

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The name of the environment to create.'
        required: true
        default: 'staging'

jobs:
  deploy-cognito-stack:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    name: Deploy the Cognito stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Deploy Cognito stack
        working-directory: cdk
        run: npm run cognito:deploy -- -c environmentName=${{ github.event.inputs.environmentName }}
